name: sm-test-job
volumes:
  site-db:

services:
  nginx:
    image: nginx:alpine
    ports:
      - 8081:80
    volumes:
      - ./:/web-app:ro
      - ./docker/site.conf:/etc/nginx/conf.d/default.conf:ro
    working_dir: /web-app
    depends_on:
      - php

  php:
    # container_name: site-php
    build:
      context: ./docker
      dockerfile: php-docker.file
    volumes:
      - ./:/web-app
    working_dir: /web-app
    user: 1000:1000
    depends_on:
      - db

  db:
    image: postgis/postgis:15-3.3-alpine
    volumes:
      - site-db:/var/lib/postgresql/data
      - ./docker/dumps:/dumps
    working_dir: /dumps
    environment:
      POSTGRES_PASSWORD: sm
      POSTGRES_USER: sm
      POSTGRES_DB: sm



